// Generated by CoffeeScript 1.7.1
(function() {
  var ViewAll, fetchmessage, fetchmessage_update, result_url, timestamp, url, urlsplt;

  url = document.URL;

  urlsplt = url.split("/");

  result_url = urlsplt[urlsplt.length - 1];

  timestamp = null;

  $(document).ready(function() {
    fetchmessage();
    window.focus(function() {
      return ViewAll();
    });
    return $("#sendmes").click(function(e) {
      var msg;
      e.preventDefault();
      msg = $("#ip").val();
      return $.ajax({
        url: '../pushMessage',
        type: 'POST',
        data: {
          msg: msg,
          rc: result_url
        },
        success: function(d) {
          $('#ip').val("");
          return $('#ip').scrollTop = 0;
        }
      });
    });
  });

  fetchmessage = function() {
    return $.ajax({
      url: '../polling',
      type: 'POST',
      dataType: 'JSON',
      data: {
        p: result_url,
        timestamp: timestamp
      },
      success: function(d) {
        var i;
        if (d.length > 0) {
          for (i in d) {
            $('#op').append(d[i].sender + " : " + d[i].msg + " <span style=\"color:grey\">" + d[i].date + "</span><br>");
          }
        }
        timestamp = d[0].timestamp;
        ViewAll();
        return fetchmessage_update();
      }
    });
  };

  fetchmessage_update = function() {
    return $.ajax({
      url: '../polling',
      type: 'POST',
      dataType: 'JSON',
      data: {
        p: result_url,
        timestamp: timestamp
      },
      success: function(d) {
        $('#op').prepend(d.sender + " : " + d.msg + " <span style=\"color:grey\">" + d.date + "</span><br>");
        return timestamp = d.timestamp;
      },
      complete: function() {
        ViewAll();
        return fetchmessage_update();
      }
    });
  };

  ViewAll = function() {
    return $.ajax({
      url: '../SetViewAll',
      type: 'POST'
    });
  };

}).call(this);

//# sourceMappingURL=chat.map
