// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $(' .chatlink').click(function(e) {
      e.preventDefault();
      return window.open($(this).attr('href'), 'chat', 'scrollbars=1,height=550,width=500');
    });
  });

}).call(this);

//# sourceMappingURL=memberlist.map
