// Generated by CoffeeScript 1.7.1
(function() {
  var UnreadMsg, ViewAll;

  $(document).ready(function() {
    UnreadMsg();
    return $(' .chatlink').click(function(e) {
      e.preventDefault();
      ViewAll();
      UnreadMsg();
      return window.open($(this).attr('href'), 'chat', 'scrollbars=1,height=550,width=500');
    });
  });

  UnreadMsg = function() {
    return $.ajax({
      url: 'memberlist/unread',
      type: 'POST',
      dataType: 'JSON',
      success: function(d) {
        var a, _results;
        _results = [];
        for (a in d) {
          _results.push($("#" + a).html(d[a]));
        }
        return _results;
      },
      complete: function(d) {
        return UnreadMsg();
      }
    });
  };

  ViewAll = function() {
    return $.ajax({
      url: 'memberlist/SetViewAll',
      type: 'POST'
    });
  };

}).call(this);

//# sourceMappingURL=memberlist.map
