// Generated by CoffeeScript 1.7.1
(function() {
  var Upload;

  $(document).ready(function() {
    $('.drop_div').on('dragenter', function(e) {
      return e.preventDefault();
    });
    $('.drop_div').on('dragover', function(e) {
      return e.preventDefault();
    });
    return $('.drop_div').on('drop', function(e) {
      e.preventDefault();
      return alert('555');
    });
  });

  Upload = function(x) {};

}).call(this);

//# sourceMappingURL=form_control2.map
