// Generated by CoffeeScript 1.7.1
(function() {
  var upload;

  $(document).ready(function() {
    $('#grom').on('dragenter', function(e) {
      return e.preventDefault();
    });
    $('#grom').on('dragover', function(e) {
      return e.preventDefault();
    });
    $('#grom').on('drop', function(e) {
      e.preventDefault();
      return upload(e.originalEvent.dataTransfer, "grom");
    });
    return $('.drop_div').on('click', function(e) {
      return e.preventDefault();
    });
  });

  upload = function(data, type) {
    var formdata;
    formdata = new FormData();
    formdata.append("img", data.files[0]);
    return $.ajax({
      xhr: function() {
        var xhr;
        xhr = new window.XMLHttpRequest();
        xhr.upload.addEventListener("progress", function(e) {
          var percentComplete;
          if (e.lengthComputable) {
            percentComplete = e.loaded / e.total;
            return $("#grom").html(percentComplete * 100);
          }
        }, false);
        return xhr;
      },
      url: 'post/uploadFile/' + type,
      type: 'POST',
      data: formdata,
      processData: false,
      contentType: false,
      success: function(d) {
        return $('#grom').html("<img src='" + d + "'>");
      }
    });
  };

}).call(this);

//# sourceMappingURL=form_control2.map
