// Generated by CoffeeScript 1.7.1
(function() {
  var count;

  count = 1;

  $(document).ready(function() {
    $('.car_img_upload_btn').click(function(e) {
      return e.preventDefault();
    });
    $('#add').click(function() {
      $('#add_upload_div').append('<div id="w' + count + '"> <div class="wait_car_img">+</div> <input type="file" class="car_file" name="file"> </div><br>');
      return count++;
    });
    return $('#del').click(function() {
      if (count > 1) {
        count--;
        $('#add_upload_div').find('.wait_car_img').last().remove();
        $('#add_upload_div').find('input').last().remove();
        return $('#add_upload_div').find('br').last().remove();
      }
    });
  });

}).call(this);

//# sourceMappingURL=form_control2.map
