// Generated by CoffeeScript 1.7.1
(function() {
  var DelImgInDir, upload;

  $(document).ready(function() {
    $(document).on('dragenter', '.in_drop_div', function(e) {
      return e.preventDefault();
    });
    $(document).on('dragover', '.in_drop_div', function(e) {
      return e.preventDefault();
    });
    $(document).on('drop', '.in_drop_div', function(e) {
      e.preventDefault();
      return upload(e.originalEvent.dataTransfer, $(this).parent().attr("id"));
    });
    $(document).on('click', '.in_drop_div', function(e) {
      e.preventDefault();
      return $(this).parent().find('input').click();
    });
    return $(document).on('click', '.del_upload_img', function(e) {
      $(this).parent().append('<div class="in_drop_div"></div>');
      $(this).parent().find('img').hide();
      DelImgInDir($(this).parent().find('img').attr('src'));
      return $(this).hide();
    });
  });

  upload = function(data, type) {
    var formdata;
    formdata = new FormData();
    formdata.append("img", data.files[0]);
    return $.ajax({
      xhr: function() {
        var xhr;
        xhr = new window.XMLHttpRequest();
        xhr.upload.addEventListener("progress", function(e) {
          var percentComplete;
          if (e.lengthComputable) {
            percentComplete = e.loaded / e.total;
            return $('#' + type + ' .in_drop_div').html(percentComplete * 100);
          }
        }, false);
        return xhr;
      },
      url: 'post/uploadFile/' + type,
      type: 'POST',
      data: formdata,
      processData: false,
      contentType: false,
      success: function(d) {
        $('#' + type + ' .in_drop_div').hide();
        return $('#' + type).append(' <img class="show_upload" src="' + d + '"> <span class="del_upload_img">X</span> ');
      }
    });
  };

  DelImgInDir = function(url) {
    return $.ajax({
      url: 'post/delImg',
      type: 'POST',
      data: {
        'del': url
      }
    });
  };

}).call(this);

//# sourceMappingURL=upload_img2.map
