// Generated by CoffeeScript 1.7.1
(function() {
  var DragSetting, count, uploadImg;

  count = 1;

  $(document).ready(function() {
    var postnote;
    $('.car_img_upload_btn').click(function(e) {
      return e.preventDefault();
    });
    $('#add').click(function() {
      $('#add_upload_div').append('<div class="wrapall" id="w' + count + '"> <div class="wait_car_img">+</div> <input type="file" class="car_file" name="file"> </div><br>');
      return count++;
    });
    $(document).on('click', '#del', function() {
      if (count > 1) {
        if ($('#add_upload_div').find('.wrapall').last().find('.show_car_upload').length === 0) {
          $('#add_upload_div').find('.wait_car_img').last().remove();
          $('#add_upload_div').find('input').last().remove();
          $('#add_upload_div').find('div').last().remove();
          $('#add_upload_div').find('br').last().remove();
          return count--;
        } else {

        }
      }
    });
    DragSetting('.wait_car_img');
    $(document).on('drop', '.wait_car_img', function(e) {
      e.preventDefault();
      return uploadImg(e.originalEvent.dataTransfer, $(this).parent().attr('id'));
    });
    $(document).on('click', '.wait_car_img', function(e) {
      e.preventDefault();
      return $(this).parent().find('input').click();
    });
    $(document).on('change', '.car_file', function(e) {
      e.preventDefault();
      return uploadImg($(this)[0], $(this).parent().attr('id'));
    });
    $(document).on('click', '.del_car_upload', function(e) {
      DelImgInDir($(this).parent().find('img').attr('src'));
      if ($(this).parent().is(':first-child')) {
        $(this).parent().html('<div class="wait_car_img">+</div> <in put type="file" class="car_file" name="file">');
        return count = 1;
      } else {
        $(this).parent().remove();
        $('#add_upload_div').find('br').last().remove();
        return count--;
      }
    });
    postnote = $('#post_note').val();
    return $(' #submit').click(function() {
      return $.ajax({
        url: '',
        type: 'POST',
        data: {
          postnote: postnote
        },
        success: function(d) {
          return alert(d);
        }
      });
    });
  });

  DragSetting = function(element) {
    $(document).on('dragenter', element, function(e) {
      return e.preventDefault();
    });
    return $(document).on('dragover', element, function(e) {
      return e.preventDefault();
    });
  };

  uploadImg = function(data, div) {
    var formdata;
    console.log(div);
    formdata = new FormData();
    formdata.append("img", data.files[0]);
    return $.ajax({
      url: '../uploadImg',
      type: 'POST',
      data: formdata,
      processData: false,
      contentType: false,
      success: function(d) {
        return $('#' + div).html('<img class="show_car_upload" src="' + d + '"><span class="del_car_upload">X</span>');
      }
    });
  };

}).call(this);

//# sourceMappingURL=post_update.map
