// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    $(" #main").click(function(e) {
      return e.preventDefault();
    });
    $("#backuplink").click(function(e) {
      e.preventDefault();
      return window.open($(this).attr('href'), 'backup', 'scrollbars=1,height=550,width=500');
    });
    $("#click_backup").click(function() {
      return $.ajax({
        url: 'Backupit',
        success: function(d) {}
      });
    });
    return $(' #click_backup').click(function() {
      return $.ajax({
        url: ''
      });
    });
  });

}).call(this);

//# sourceMappingURL=users_pagecontrol.map
