// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    $(" #main").click(function(e) {
      return e.preventDefault();
    });
    $("#click_backup").click(function() {
      return $.ajax({
        url: 'Backupit',
        success: function(d) {
          alert('Backup สำเร็จ');
          return self.close();
        }
      });
    });
    $(' .edit').click(function(e) {
      e.preventDefault();
      return window.open($(this).attr('href'), 'edit', 'scrollbars=1,height=450,width=500');
    });
    $(' .del').click(function() {
      if (confirm('คุณต้องการที่จะลบ?')) {
        return true;
      } else {
        return false;
      }
    });
    $(" #backuplink").click(function(e) {
      e.preventDefault();
      return window.open($(this).attr('href'), 'backup', 'scrollbars=1,height=550,width=500');
    });
    $(" #createlink").click(function(e) {
      e.preventDefault();
      $(' #content').html('');
      return $(' #content').load($(this).attr('href'));
    });
    return $('#create_submit').click(function(e) {
      e.preventDefault();
      return $.ajax({
        url: 'users/insert',
        type: 'POST',
        data: {
          username: $("#user").val(),
          password: $('#pass').val(),
          "class": $('#role').val()
        },
        success: function(d) {
          if (d === "fuck") {
            return alert("ชื่อผู้ใช้ซ้ำครับ");
          } else {
            return location.reload();
          }
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=users_pagecontrol.map
