// Generated by CoffeeScript 1.7.1
(function() {
  var choice, search, val;

  choice = "header";

  val = "header";

  $(document).on('keyup', '#search', function() {
    return search();
  });

  $(document).on('change', '.radio', function() {
    if ($(" #header").is(':checked')) {
      choice = "header";
      return search();
    } else {
      choice = "deatail";
      return search();
    }
  });

  $(document).on('change', '#var', function() {
    val = $(this).val();
    return search();
  });

  $(document).on('click', '#x_btn', function(e) {
    e.preventDefault();
    $("#search").val("");
    return $('#result').html('');
  });

  search = function() {
    return $.ajax({
      url: 'search/fetch',
      type: 'POST',
      data: {
        word: $("#search").val(),
        choice: val
      },
      dataType: 'JSON',
      success: function(d) {
        var i, _results;
        if ($("#search").val() !== "") {
          if (d.length > 0) {
            $('#result').html('');
            _results = [];
            for (i in d) {
              _results.push($('#result').append('<a href="topic/id/' + d[i].topicID + '"> <div class="tp"> <span class="header">' + d[i].header + '</span><br> <span class="descrip">รายละเอียด : ' + d[i].detail + '</span><br> <span class="descrip">การดำเนินงาน : ขั้นตอนที่ ' + d[i].status + '</span><br> <span class="descrip">สร้างโดย : ' + d[i].username + '</span><br> </div> </a>'));
            }
            return _results;
          } else {
            return $('#result').html('');
          }
        } else {
          return $('#result').html('');
        }
      }
    });
  };

}).call(this);

//# sourceMappingURL=search.map
