// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    $(' .tpmg').click(function() {
      var a;
      a = confirm('คุณแน่ใจที่จะเปลี่ยนแปลงกระทู้ใช่หรือไม่');
      if (a) {
        return true;
      } else {
        return false;
      }
    });
    $(' .box_in_head').click(function() {
      $(this).parent().find('img').toggle();
      $(this).parent().find('br').toggle();
      if ($(this).find('.arrow').html() === '▲') {
        $(this).find('.arrow').html('▼');
        return $(this).parent().find('br').last().remove();
      } else {
        $(this).find('.arrow').html('▲');
        return $(this).parent().append('<br>');
      }
    });
    return $(' #verify').click(function(e) {
      var result_url, url, urlsplt;
      url = document.URL;
      urlsplt = url.split("/");
      result_url = urlsplt[urlsplt.length - 1];
      e.preventDefault();
      return $.ajax({
        url: '../verify',
        type: 'POST',
        data: {
          id: result_url
        },
        success: function(d) {
          return location.replace("");
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=topic_control.map
