// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $(' .box_in_head').click(function() {
      $(this).parent().find('img').toggle();
      $(this).parent().find('br').toggle();
      if ($(this).find('.arrow').html() === '▲') {
        $(this).find('.arrow').html('▼');
        return $(this).parent().find('br').last().remove();
      } else {
        $(this).find('.arrow').html('▲');
        return $(this).parent().append('<br>');
      }
    });
  });

}).call(this);

//# sourceMappingURL=topic_control.map
