// Generated by CoffeeScript 1.7.1
(function() {
  var AddCarUploadDiv, AddCarUploadDiv2, AddCarUploadDiv3, DelCarUpload, DelImgInDir, DragSetting, ManageCarImg, count, count2, count3, fetchImg, formControl, tpid, uploadDoc, uploadImg, url, urlsplt;

  url = document.URL;

  urlsplt = url.split("/");

  tpid = urlsplt[urlsplt.length - 1];

  count = 0;

  count2 = 0;

  count3 = 0;

  $(document).ready(function() {
    DelCarUpload("");
    DelCarUpload("2");
    DelCarUpload("3");
    formControl("");
    formControl("2");
    formControl("3");
    fetchImg();
    DragSetting('.in_drop_div');
    $(document).on('drop', '.in_drop_div', function(e) {
      e.preventDefault();
      return uploadDoc(e.originalEvent.dataTransfer, $(this).parent().attr("id"));
    });
    $(document).on('click', '.in_drop_div', function(e) {
      e.preventDefault();
      return $(this).parent().find('input').click();
    });
    $(document).on('change', '.ip_upload1', function(e) {
      e.preventDefault();
      return uploadDoc($(this)[0], $(this).parent().attr("id"));
    });
    $(document).on('click', '.del_upload_img', function(e) {
      $(this).parent().append('<div class="in_drop_div"></div>');
      $(this).parent().find('img').hide();
      DelImgInDir($(this).parent().find('img').attr('src'));
      return $(this).hide();
    });
    ManageCarImg("");
    ManageCarImg("2");
    ManageCarImg("3");
    return $("#submit").click(function(e) {
      e.preventDefault();
      return $.ajax({
        url: '../Pushdata',
        type: 'POST',
        data: {
          header: $("#post_header").val(),
          note: $("#post_note").val(),
          detail: $("#post_detail").val(),
          note2: $("#post_note2").val(),
          note3: $("#post_note3").val(),
          topicid: tpid
        },
        success: function(d) {
          return window.location = "../../";
        }
      });
    });
  });

  fetchImg = function() {
    return $.ajax({
      url: '../fetchImg',
      type: 'POST',
      data: {
        topicid: tpid
      },
      dataType: 'JSON',
      success: function(d) {
        var i, ii, iii, _results;
        if (typeof d.grom !== 'undefined') {
          $('#grom .in_drop_div').hide();
          $('#grom').append(' <img class="show_upload" src="../../file/' + tpid + "/grom/" + d.grom + '"><span class="del_upload_img">X</span> ');
        }
        if (typeof d.crame !== 'undefined') {
          $('#crame .in_drop_div').hide();
          $('#crame').append(' <img class="show_upload" src="../../file/' + tpid + "/crame/" + d.crame + '"><span class="del_upload_img">X</span> ');
        }
        if (typeof d.drive !== 'undefined') {
          $('#drive .in_drop_div').hide();
          $('#drive').append(' <img class="show_upload" src="../../file/' + tpid + "/drive/" + d.drive + '"><span class="del_upload_img">X</span> ');
        }
        if (typeof d.cussy !== 'undefined') {
          $('#cussy .in_drop_div').hide();
          $('#cussy').append(' <img class="show_upload" src="../../file/' + tpid + "/cussy/" + d.cussy + '"><span class="del_upload_img">X</span> ');
        }
        if (typeof d.fin !== 'undefined') {
          $('#fin .in_drop_div').hide();
          $('#fin').append(' <img class="show_upload" src="../../file/' + tpid + "/fin/" + d.fin + '"><span class="del_upload_img">X</span> ');
        }
        for (i in d.img) {
          AddCarUploadDiv();
          $('#w' + count).html('<img class="show_car_upload" src="../../file/' + tpid + "/img/" + d.img[i] + '"><span class="del_car_upload">X</span>');
          count++;
        }
        for (ii in d.img2) {
          AddCarUploadDiv2();
          $('#ww' + count2).html('<img class="show_car_upload2" src="../../file/' + tpid + "/img2/" + d.img2[ii] + '"><span class="del_car_upload2">X</span>');
          count2++;
        }
        _results = [];
        for (iii in d.img3) {
          AddCarUploadDiv3();
          $('#www' + count3).html('<img class="show_car_upload3" src="../../file/' + tpid + "/img3/" + d.img3[iii] + '"><span class="del_car_upload3">X</span>');
          _results.push(count3++);
        }
        return _results;
      }
    });
  };

  AddCarUploadDiv = function() {
    return $('#add_upload_div').append('<div class="wrapall" id="w' + count + '"> <div class="wait_car_img">+</div> <input type="file" class="car_file" name="file"> </div><br>');
  };

  AddCarUploadDiv2 = function() {
    return $('#add_upload_div2').append('<div class="wrapall2" id="ww' + count2 + '"> <div class="wait_car_img2">+</div> <input type="file" class="car_file2" name="file"> </div><br>');
  };

  AddCarUploadDiv3 = function() {
    return $('#add_upload_div3').append('<div class="wrapall3" id="www' + count3 + '"> <div class="wait_car_img3">+</div> <input type="file" class="car_file3" name="file"> </div><br>');
  };

  DelImgInDir = function(url) {
    return $.ajax({
      url: 'post/delImg',
      type: 'POST',
      data: {
        'del': url
      }
    });
  };

  formControl = function(num) {
    $('.car_img_upload_btn' + num).click(function(e) {
      return e.preventDefault();
    });
    $('#add' + num).click(function() {
      var c, w;
      if (num === "") {
        c = count;
      } else if (num === "2") {
        c = count2;
      } else if (num === "3") {
        c = count3;
      }
      if (num === "") {
        w = "";
      } else if (num === "2") {
        w = "w";
      } else if (num === "3") {
        w = "ww";
      }
      $('#add_upload_div' + num).append('<div class="wrapall' + num + '" id="w' + w + c + '"> <div class="wait_car_img' + num + '">+</div> <input type="file" class="car_file' + num + '" name="file"> </div><br>');
      if (num === "") {
        return count++;
      } else if (num === "2") {
        return count2++;
      } else if (num === "3") {
        return count3++;
      }
    });
    return $(document).on('click', '#del' + num, function() {
      var cc;
      if (num === "") {
        cc = count;
      } else if (num === "2") {
        cc = count2;
      } else if (num === "3") {
        cc = count3;
      }
      if (cc > 0) {
        if ($('#add_upload_div' + num).find('.wrapall' + num).last().find('.show_car_upload' + num).length === 0) {
          $('#add_upload_div' + num).find('.wait_car_img' + num).last().remove();
          $('#add_upload_div' + num).find('input').last().remove();
          $('#add_upload_div' + num).find('div').last().remove();
          $('#add_upload_div' + num).find('br').last().remove();
          if (num === "") {
            return count--;
          } else if (num === "2") {
            return count2--;
          } else if (num === "3") {
            return count3--;
          }
        } else {

        }
      }
    });
  };

  uploadDoc = function(data, type) {
    var formdata;
    formdata = new FormData();
    formdata.append("img", data.files[0]);
    return $.ajax({
      xhr: function() {
        var xhr;
        xhr = new window.XMLHttpRequest();
        xhr.upload.addEventListener("progress", function(e) {
          var percentComplete;
          if (e.lengthComputable) {
            percentComplete = e.loaded / e.total;
            return $('#' + type + ' .in_drop_div').html(percentComplete * 100);
          }
        }, false);
        return xhr;
      },
      url: '../../post/uploadFile/' + type,
      type: 'POST',
      data: formdata,
      processData: false,
      contentType: false,
      success: function(d) {
        $('#' + type + ' .in_drop_div').hide();
        return $('#' + type).append(' <img class="show_upload" src="../../' + d + '"> <span class="del_upload_img">X</span> ');
      }
    });
  };

  uploadImg = function(data, div, num) {
    var formdata, w;
    if (num === "") {
      w = "";
      url = '../uploadImg';
    } else if (num === "2") {
      w = "w";
      url = '../uploadImg2';
    } else if (num === "3") {
      w = "ww";
      url = '../uploadImg3';
    }
    formdata = new FormData();
    formdata.append("img", data.files[0]);
    return $.ajax({
      url: url,
      type: 'POST',
      data: formdata,
      processData: false,
      contentType: false,
      success: function(d) {
        return $('#' + div).html('<img class="show_car_upload' + num + '" src="../../' + d + '"><span class="del_car_upload' + num + '">X</span>');
      }
    });
  };

  DelCarUpload = function(num) {
    return $(document).on('click', '.del_car_upload' + num, function(e) {
      DelImgInDir($(this).parent().find('img').attr('src'));
      if ($(this).parent().is(':first-child')) {
        $(this).parent().html('<div class="wait_car_img' + num + '">+</div> <in put type="file" class="car_file' + num + '" name="file">');
        if (num === "") {
          return count = 1;
        } else if (num === "2") {
          return count2 = 1;
        } else if (num === "3") {
          return count3 = 1;
        }
      } else {
        $(this).parent().remove();
        $('#add_upload_div' + num).find('br').last().remove();
        if (num === "") {
          return count--;
        } else if (num === "2") {
          return count2--;
        } else if (num === "3") {
          return count3--;
        }
      }
    });
  };

  DelImgInDir = function(url) {
    var aa;
    aa = url.split("../");
    return $.ajax({
      url: '../delImg',
      type: 'POST',
      data: {
        'del': aa[aa.length - 1]
      }
    });
  };

  ManageCarImg = function(num) {
    DragSetting('.wait_car_img' + num);
    $(document).on('drop', '.wait_car_img' + num, function(e) {
      e.preventDefault();
      return uploadImg(e.originalEvent.dataTransfer, $(this).parent().attr('id'), num);
    });
    $(document).on('click', '.wait_car_img' + num, function(e) {
      e.preventDefault();
      return $(this).parent().find('input').click();
    });
    $(document).on('change', '.car_file' + num, function(e) {
      e.preventDefault();
      return uploadImg($(this)[0], $(this).parent().attr('id'), num);
    });
    return $(document).on('click', '.del_car_upload' + num, function(e) {
      DelImgInDir($(this).parent().find('img').attr('src'));
      if ($(this).parent().is(':first-child')) {
        $(this).parent().html('<div class="wait_car_img' + num + '">+</div> <in put type="file" class="car_file' + num + '" name="file">');
        if (num === "") {
          return count = 1;
        } else if (num === "2") {
          return count2 = 1;
        } else if (num === "3") {
          return count3 = 1;
        }
      } else {
        $(this).parent().remove();
        $('#add_upload_div' + num).find('br').last().remove();
        if (num === "") {
          return count--;
        } else if (num === "2") {
          return count2--;
        } else if (num === "3") {
          return count3--;
        }
      }
    });
  };

  DragSetting = function(element) {
    $(document).on('dragenter', element, function(e) {
      return e.preventDefault();
    });
    return $(document).on('dragover', element, function(e) {
      return e.preventDefault();
    });
  };

}).call(this);

//# sourceMappingURL=edit.map
