// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    var PreventHtmlTag;
    $.rb_Reply = function(a, q) {
      var aptemplate, data, pretemplate, topic;
      data = $.extend({
        status: "",
        header: "",
        user: "",
        date: "",
        last_update: "",
        url: ""
      }, a);
      topic = '<a href="' + data.url + '"><div class="reply">' + '<span class="rep_status">' + data.status + '</span>' + '<span class="head">' + data.header + '</span><br>' + '<span class="descrip">สร้างโดย : </span>' + data.user + '<br>' + '<span class="descrip">อัพเดท : </span>' + data.last_update + '<br>' + '<span class="descrip">วันที่สร้าง : </span>' + data.date + '<br><br>' + '</div></a>';
      aptemplate = function() {
        return $("#content").append(topic);
      };
      pretemplate = function() {
        return $("#content").prepend(topic);
      };
      if (q === "ap") {
        return aptemplate();
      } else if (q === "pre") {
        return pretemplate();
      }
      return false;
    };
    return PreventHtmlTag = function(prob) {
      return prob.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    };
  })(jQuery);

}).call(this);

//# sourceMappingURL=tp_plugin.map
